In [35]:
# imports
import autograd.numpy as np
from autograd import grad

In [36]:
# linear 
def f(x, y):
    return np.dot(np.transpose(x), y)

def df(x, y):
    return y

auto = grad(f)

for i in range(10):
    x = np.random.random((2, 1))
    y = np.random.random((2, 1))
    print(f'Input x: \n{x}')
    print(f'Input y: \n{y}')
    print(f'Auto: \n{auto(x, y)}\nTheoretical: \n{df(x, y)}\n')

Input x: 
[[0.44262838]
 [0.48990527]]
Input y: 
[[0.47138656]
 [0.55990872]]
Auto: 
[[0.47138656]
 [0.55990872]]
Theoretical: 
[[0.47138656]
 [0.55990872]]

Input x: 
[[0.65653171]
 [0.68313449]]
Input y: 
[[0.05991847]
 [0.09038479]]
Auto: 
[[0.05991847]
 [0.09038479]]
Theoretical: 
[[0.05991847]
 [0.09038479]]

Input x: 
[[0.07020532]
 [0.22137403]]
Input y: 
[[0.10081293]
 [0.73493292]]
Auto: 
[[0.10081293]
 [0.73493292]]
Theoretical: 
[[0.10081293]
 [0.73493292]]

Input x: 
[[0.08492178]
 [0.76169149]]
Input y: 
[[0.60413068]
 [0.63859539]]
Auto: 
[[0.60413068]
 [0.63859539]]
Theoretical: 
[[0.60413068]
 [0.63859539]]

Input x: 
[[0.25027975]
 [0.67913778]]
Input y: 
[[0.52351572]
 [0.90518336]]
Auto: 
[[0.52351572]
 [0.90518336]]
Theoretical: 
[[0.52351572]
 [0.90518336]]

Input x: 
[[0.53611463]
 [0.03146428]]
Input y: 
[[0.33490287]
 [0.87003748]]
Auto: 
[[0.33490287]
 [0.87003748]]
Theoretical: 
[[0.33490287]
 [0.87003748]]

Input x: 
[[0.63895868]
 [0.02015131]]
Input y: 
[[0

In [37]:
# quadratic
def f(x, A):
    return np.dot(np.dot(np.transpose(x), A), x)

def df(x, A):
    return np.dot((A + np.transpose(A)), x)

auto = grad(f)

for i in range(10):
    x = np.random.random((2, 1))
    A = np.random.random((2, 2))
    print(f'Input x: \n{x}')
    print(f'Input A: \n{A}')
    print(f'Auto: \n{auto(x, A)}\nTheoretical: \n{df(x, A)}\n')

Input x: 
[[0.79224549]
 [0.9449621 ]]
Input A: 
[[0.8099862  0.53362071]
 [0.20428439 0.75376488]]
Auto: 
[[1.98070819]
 [2.00916049]]
Theoretical: 
[[1.98070819]
 [2.00916049]]

Input x: 
[[0.33136368]
 [0.38250886]]
Input A: 
[[0.55173011 0.90682621]
 [0.57972865 0.44832335]]
Auto: 
[[0.93426704]
 [0.83556559]]
Theoretical: 
[[0.93426704]
 [0.83556559]]

Input x: 
[[0.97030217]
 [0.45761868]]
Input A: 
[[0.79515205 0.97693663]
 [0.91914605 0.6786134 ]]
Auto: 
[[2.41075838]
 [2.46086547]]
Theoretical: 
[[2.41075838]
 [2.46086547]]

Input x: 
[[0.2603639 ]
 [0.11518449]]
Input A: 
[[0.69773196 0.74738186]
 [0.58665378 0.08680116]]
Auto: 
[[0.51698864]
 [0.36733102]]
Theoretical: 
[[0.51698864]
 [0.36733102]]

Input x: 
[[0.06856054]
 [0.98952509]]
Input A: 
[[0.89673048 0.42764348]
 [0.95164608 0.13920767]]
Auto: 
[[1.48780229]
 [0.3700638 ]]
Theoretical: 
[[1.48780229]
 [0.3700638 ]]

Input x: 
[[0.47473045]
 [0.02065274]]
Input A: 
[[0.4035264  0.50873626]
 [0.52962841 0.25088451]]


In [38]:
# trace of quadratic
def f(x, A):
    return np.trace(np.dot(np.dot(np.transpose(x), A), x))

def df(x, A):
    return np.dot((A + np.transpose(A)), x)

auto = grad(f)

for i in range(10):
    x = np.random.random((2, 1))
    A = np.random.random((2, 2))
    print(f'Input x: \n{x}')
    print(f'Input A: \n{A}')
    print(f'Auto: \n{auto(x, A)}\nTheoretical: \n{df(x, A)}\n')

Input x: 
[[0.90878874]
 [0.00532771]]
Input A: 
[[0.10499988 0.00333103]
 [0.92754805 0.44594611]]
Auto: 
[[0.19580487]
 [0.85072417]]
Theoretical: 
[[0.19580487]
 [0.85072417]]

Input x: 
[[0.7342805 ]
 [0.01976592]]
Input A: 
[[0.25729846 0.37682419]
 [0.09108014 0.86940254]]
Auto: 
[[0.38710704]
 [0.37794211]]
Theoretical: 
[[0.38710704]
 [0.37794211]]

Input x: 
[[0.61081746]
 [0.43449147]]
Input A: 
[[0.85680812 0.77458707]
 [0.97946068 0.59912864]]
Auto: 
[[1.80882549]
 [1.59203555]]
Theoretical: 
[[1.80882549]
 [1.59203555]]

Input x: 
[[0.88415546]
 [0.12081757]]
Input A: 
[[0.48941765 0.44893455]
 [0.75399851 0.08095417]]
Auto: 
[[1.01077803]
 [1.08314121]]
Theoretical: 
[[1.01077803]
 [1.08314121]]

Input x: 
[[0.00446503]
 [0.91510008]]
Input A: 
[[0.14781135 0.58183318]
 [0.91768759 0.67007175]]
Auto: 
[[1.37353153]
 [1.23306083]]
Theoretical: 
[[1.37353153]
 [1.23306083]]

Input x: 
[[0.57446745]
 [0.0592651 ]]
Input A: 
[[0.40878314 0.91670715]
 [0.14825649 0.02269916]]


In [39]:
# ReLU
def f(w, x):
    return np.maximum(np.dot(np.transpose(w), x), 0)

def df(w, x):
    dw = 1 if np.dot(np.transpose(w), x) > 0 else 0
    return dw * x

auto = grad(f)

for i in range(10):
    w = np.random.randint(-10, 10, (2, 1))
    x = np.random.randint(-10, 10, (2, 1))
    print(f'Input w: \n{w}')
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(w, x)}\nTheoretical: \n{df(w, x)}\n')

Input w: 
[[-10]
 [  5]]
Input x: 
[[ 0]
 [-8]]
Auto: 
[[0]
 [0]]
Theoretical: 
[[0]
 [0]]

Input w: 
[[-2]
 [ 5]]
Input x: 
[[ 0]
 [-7]]
Auto: 
[[0]
 [0]]
Theoretical: 
[[0]
 [0]]

Input w: 
[[7]
 [8]]
Input x: 
[[-2]
 [ 3]]
Auto: 
[[-2]
 [ 3]]
Theoretical: 
[[-2]
 [ 3]]

Input w: 
[[ 0]
 [-6]]
Input x: 
[[-2]
 [ 5]]
Auto: 
[[0]
 [0]]
Theoretical: 
[[0]
 [0]]

Input w: 
[[-8]
 [ 4]]
Input x: 
[[-1]
 [-3]]
Auto: 
[[0]
 [0]]
Theoretical: 
[[0]
 [0]]

Input w: 
[[8]
 [8]]
Input x: 
[[ 8]
 [-1]]
Auto: 
[[ 8]
 [-1]]
Theoretical: 
[[ 8]
 [-1]]

Input w: 
[[6]
 [4]]
Input x: 
[[-8]
 [ 5]]
Auto: 
[[0]
 [0]]
Theoretical: 
[[0]
 [0]]

Input w: 
[[-5]
 [-4]]
Input x: 
[[-3]
 [-3]]
Auto: 
[[-3]
 [-3]]
Theoretical: 
[[-3]
 [-3]]

Input w: 
[[-4]
 [ 2]]
Input x: 
[[-6]
 [ 6]]
Auto: 
[[-6]
 [ 6]]
Theoretical: 
[[-6]
 [ 6]]

Input w: 
[[-3]
 [ 0]]
Input x: 
[[ -9]
 [-10]]
Auto: 
[[ -9]
 [-10]]
Theoretical: 
[[ -9]
 [-10]]



In [40]:
# Linear Regression
def f(w, x, y):
    total = 0
    for i in range(len(x)):
        total += 1/2 * (np.dot(np.transpose(w), x[i]) - y[i])**2
    return total

def df(w, x, y):
    total = 0
    for i in range(len(x)):
        total += (np.dot(np.transpose(w), x[i]) - y[i]) * x[i]
    return total

auto = grad(f)

for i in range(10):
    w = np.random.random((2, 1))
    x = np.random.random((2, 2))
    y = np.random.random((2, 1))
    print(f'Input w: \n{w}')
    print(f'Input x: \n{x}')
    print(f'Input y: \n{y}')
    print(f'Auto: \n{auto(w, x, y)}\nTheoretical: \n{df(w, x, y)}\n')
    

Input w: 
[[0.47301516]
 [0.97677822]]
Input x: 
[[0.91953694 0.44631964]
 [0.5782657  0.24325814]]
Input y: 
[[0.93162082]
 [0.42573217]]
Auto: 
[[-0.00643856]
 [-0.00632075]]
Theoretical: 
[-0.00643856 -0.00632075]

Input w: 
[[0.6273012 ]
 [0.35357159]]
Input x: 
[[0.20826284 0.543298  ]
 [0.76013445 0.79956051]]
Input y: 
[[0.62297637]
 [0.19803477]]
Auto: 
[[0.36428733]
 [0.28583475]]
Theoretical: 
[0.36428733 0.28583475]

Input w: 
[[0.40988235]
 [0.12212001]]
Input x: 
[[0.21905166 0.36094392]
 [0.53729537 0.02564334]]
Input y: 
[[0.46241818]
 [0.78360716]]
Auto: 
[[-0.37298886]
 [-0.1329563 ]]
Theoretical: 
[-0.37298886 -0.1329563 ]

Input w: 
[[0.86502807]
 [0.14879869]]
Input x: 
[[0.49612337 0.08123921]
 [0.1015099  0.08305519]]
Input y: 
[[0.00397211]
 [0.16974027]]
Auto: 
[[0.20988091]
 [0.02974564]]
Theoretical: 
[0.20988091 0.02974564]

Input w: 
[[0.87980368]
 [0.55790581]]
Input x: 
[[0.40899443 0.68222941]
 [0.80324391 0.31474703]]
Input y: 
[[0.83703067]
 [0.05733102

In [41]:
# Multivariate Gaussian Trace
def f(x, A):
    return np.exp(-np.trace(np.dot(np.dot(np.transpose(x), A), x)))

def df(x, A):
    return -np.exp(-np.trace(np.dot(np.dot(np.transpose(x), A), x))) * np.dot((A + np.transpose(A)), x)

auto = grad(f)

for i in range(10):
    x = np.random.random((2, 1))
    A = np.random.random((2, 2))
    print(f'Input x: \n{x}')
    print(f'Input A: \n{A}')
    print(f'Auto: \n{auto(x, A)}\nTheoretical: \n{df(x, A)}\n')

Input x: 
[[0.15521598]
 [0.10404411]]
Input A: 
[[0.2755198  0.82665283]
 [0.87450158 0.16513839]]
Auto: 
[[-0.25326828]
 [-0.2878874 ]]
Theoretical: 
[[-0.25326828]
 [-0.2878874 ]]

Input x: 
[[0.05641775]
 [0.41004299]]
Input A: 
[[0.72944749 0.3181665 ]
 [0.87622066 0.75263779]]
Auto: 
[[-0.48918583]
 [-0.58543514]]
Theoretical: 
[[-0.48918583]
 [-0.58543514]]

Input x: 
[[0.50492923]
 [0.39396844]]
Input A: 
[[0.12917765 0.31817989]
 [0.60793503 0.86403855]]
Auto: 
[[-0.34859648]
 [-0.80825707]]
Theoretical: 
[[-0.34859648]
 [-0.80825707]]

Input x: 
[[0.55229492]
 [0.75297337]]
Input A: 
[[0.10424169 0.41145528]
 [0.34868491 0.04090319]]
Auto: 
[[-0.47436342]
 [-0.33216676]]
Theoretical: 
[[-0.47436342]
 [-0.33216676]]

Input x: 
[[0.99187277]
 [0.07242865]]
Input A: 
[[0.30668894 0.31042934]
 [0.29893618 0.50025384]]
Auto: 
[[-0.46069183]
 [-0.47788328]]
Theoretical: 
[[-0.46069183]
 [-0.47788328]]

Input x: 
[[0.82225522]
 [0.60518636]]
Input A: 
[[0.39765512 0.12924678]
 [0.64

In [42]:
# Multivariate Gaussian
def f(x, A):
    return np.exp(-np.dot(np.dot(np.transpose(x), A), x))

def df(x, A):
    return -np.exp(-np.dot(np.dot(np.transpose(x), A), x)) * np.dot((A + np.transpose(A)), x)

auto = grad(f)

for i in range(10):
    x = np.random.random((2, 1))
    A = np.random.random((2, 2))
    print(f'Input x: \n{x}')
    print(f'Input A: \n{A}')
    print(f'Auto: \n{auto(x, A)}\nTheoretical: \n{df(x, A)}\n')

Input x: 
[[0.46300253]
 [0.81783491]]
Input A: 
[[0.50478074 0.43488505]
 [0.81661799 0.16453446]]
Auto: 
[[-0.74621716]
 [-0.42470828]]
Theoretical: 
[[-0.74621716]
 [-0.42470828]]

Input x: 
[[0.36532578]
 [0.18277487]]
Input A: 
[[0.39350903 0.21456613]
 [0.18525341 0.33368902]]
Auto: 
[[-0.3294393]
 [-0.2448851]]
Theoretical: 
[[-0.3294393]
 [-0.2448851]]

Input x: 
[[0.60748365]
 [0.66645305]]
Input A: 
[[0.53047689 0.02955775]
 [0.34417143 0.98526386]]
Auto: 
[[-0.40770913]
 [-0.70278012]]
Theoretical: 
[[-0.40770913]
 [-0.70278012]]

Input x: 
[[0.35936198]
 [0.91040354]]
Input A: 
[[0.43857128 0.91991402]
 [0.31330219 0.53740715]]
Auto: 
[[-0.58140085]
 [-0.57483034]]
Theoretical: 
[[-0.58140085]
 [-0.57483034]]

Input x: 
[[0.89931029]
 [0.17027048]]
Input A: 
[[0.75486052 0.76855463]
 [0.90809995 0.34122755]]
Auto: 
[[-0.68352534]
 [-0.6755562 ]]
Theoretical: 
[[-0.68352534]
 [-0.6755562 ]]

Input x: 
[[0.6594766 ]
 [0.95675512]]
Input A: 
[[0.55872728 0.89441572]
 [0.059595

In [43]:
# Sigmoid
def f(x):
    return (1 + np.exp(-x))**-1

def df(x):
    return (1 + np.exp(-x))**-1 * (1 - (1 + np.exp(-x))**-1)

auto = grad(f)

for i in range(10):
    x = np.random.random()
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(x)}\nTheoretical: \n{df(x)}\n')

Input x: 
0.7406166434229556
Auto: 
0.2186247206237489
Theoretical: 
0.21862472062374885

Input x: 
0.07509221908300479
Auto: 
0.24964790336405762
Theoretical: 
0.24964790336405762

Input x: 
0.6586170705022484
Auto: 
0.22473500427087634
Theoretical: 
0.22473500427087634

Input x: 
0.170369506890775
Auto: 
0.24819462948659718
Theoretical: 
0.24819462948659718

Input x: 
0.33299320933988696
Auto: 
0.24319581365490267
Theoretical: 
0.24319581365490264

Input x: 
0.3341005097827102
Auto: 
0.24315131896184883
Theoretical: 
0.2431513189618488

Input x: 
0.07533877169408676
Auto: 
0.24964558965811925
Theoretical: 
0.24964558965811925

Input x: 
0.9114217707185962
Auto: 
0.20450694382106943
Theoretical: 
0.2045069438210694

Input x: 
0.1434969318262792
Auto: 
0.24871744327369916
Theoretical: 
0.2487174432736991

Input x: 
0.8099532993490527
Auto: 
0.2130977618959234
Theoretical: 
0.21309776189592336



In [52]:
# Logistic Regression Objective
def f(w, x):
    return (1 + np.exp(-np.dot(np.transpose(w), x)))**-1

def df(w, x):
    z = np.dot(np.transpose(w), x)
    return (1 + np.exp(-z))**-1 * (1 - (1 + np.exp(-z))**-1) * x

auto = grad(f)

for i in range(10):
    w = np.random.random((2, 1))
    x = np.random.random((2, 1))
    print(f'Input w: \n{w}')
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(w, x)}\nTheoretical: \n{df(w, x)}\n')

Input w: 
[[0.17886206]
 [0.5708747 ]]
Input x: 
[[0.89838511]
 [0.80554915]]
Auto: 
[[0.20428961]
 [0.18317904]]
Theoretical: 
[[0.20428961]
 [0.18317904]]

Input w: 
[[0.01204881]
 [0.65960205]]
Input x: 
[[0.32943501]
 [0.54705856]]
Auto: 
[[0.0796782 ]
 [0.13231332]]
Theoretical: 
[[0.0796782 ]
 [0.13231332]]

Input w: 
[[0.78991843]
 [0.68642576]]
Input x: 
[[0.10433706]
 [0.74118855]]
Auto: 
[[0.0239316 ]
 [0.17000506]]
Theoretical: 
[[0.0239316 ]
 [0.17000506]]

Input w: 
[[0.63877934]
 [0.19231053]]
Input x: 
[[0.52032836]
 [0.72022427]]
Auto: 
[[0.12312967]
 [0.17043271]]
Theoretical: 
[[0.12312967]
 [0.17043271]]

Input w: 
[[0.21005422]
 [0.28367904]]
Input x: 
[[0.94070848]
 [0.76273749]]
Auto: 
[[0.22538231]
 [0.18274263]]
Theoretical: 
[[0.22538231]
 [0.18274263]]

Input w: 
[[0.14482129]
 [0.62649824]]
Input x: 
[[0.10162462]
 [0.24969263]]
Auto: 
[[0.02522101]
 [0.06196825]]
Theoretical: 
[[0.02522101]
 [0.06196825]]

Input w: 
[[0.20851232]
 [0.73786127]]
Input x: 
[[0

In [45]:
# L1 Norm
def f(x):
    return sum(abs(i) for i in x)

def df(x):
    return np.sign(x)

auto = grad(f)

for i in range(10):
    x = np.random.randint(-10, 10, (2, 1))
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(x)}\nTheoretical: \n{df(x)}\n')

Input x: 
[[4]
 [6]]
Auto: 
[[1]
 [1]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[-7]
 [-6]]
Auto: 
[[-1]
 [-1]]
Theoretical: 
[[-1]
 [-1]]

Input x: 
[[-5]
 [-7]]
Auto: 
[[-1]
 [-1]]
Theoretical: 
[[-1]
 [-1]]

Input x: 
[[6]
 [0]]
Auto: 
[[1]
 [0]]
Theoretical: 
[[1]
 [0]]

Input x: 
[[ 0]
 [-4]]
Auto: 
[[ 0]
 [-1]]
Theoretical: 
[[ 0]
 [-1]]

Input x: 
[[ 8]
 [-1]]
Auto: 
[[ 1]
 [-1]]
Theoretical: 
[[ 1]
 [-1]]

Input x: 
[[-8]
 [-5]]
Auto: 
[[-1]
 [-1]]
Theoretical: 
[[-1]
 [-1]]

Input x: 
[[-2]
 [-7]]
Auto: 
[[-1]
 [-1]]
Theoretical: 
[[-1]
 [-1]]

Input x: 
[[ 1]
 [-7]]
Auto: 
[[ 1]
 [-1]]
Theoretical: 
[[ 1]
 [-1]]

Input x: 
[[-9]
 [-5]]
Auto: 
[[-1]
 [-1]]
Theoretical: 
[[-1]
 [-1]]



In [61]:
# L2 Norm
def f(x):
    return np.sqrt(sum(np.power(i, 2) for i in x))

def df(x):
    return x/np.sqrt(sum(np.power(i, 2) for i in x))

auto = grad(f)

for i in range(10):
    x = np.random.random((4, 1))
    print(f'Input x: \n{x}')
    print(f(x))
    print(f'Auto: \n{auto(x)}\nTheoretical: \n{df(x)}\n')

Input x: 
[[0.79165298]
 [0.85358153]
 [0.45346406]
 [0.93756892]]
[1.56204386]
Auto: 
[[0.50680586]
 [0.54645171]
 [0.29030175]
 [0.60021933]]
Theoretical: 
[[0.50680586]
 [0.54645171]
 [0.29030175]
 [0.60021933]]

Input x: 
[[0.20571784]
 [0.8157766 ]
 [0.04240353]
 [0.43408457]]
[0.94764907]
Auto: 
[[0.2170823 ]
 [0.8608425 ]
 [0.04474603]
 [0.45806468]]
Theoretical: 
[[0.2170823 ]
 [0.8608425 ]
 [0.04474603]
 [0.45806468]]

Input x: 
[[0.03940126]
 [0.19562724]
 [0.45162294]
 [0.59252902]]
[0.77128231]
Auto: 
[[0.0510854 ]
 [0.25363896]
 [0.58554816]
 [0.76823884]]
Theoretical: 
[[0.0510854 ]
 [0.25363896]
 [0.58554816]
 [0.76823884]]

Input x: 
[[0.26276255]
 [0.06626933]
 [0.46299741]
 [0.36030165]]
[0.64623499]
Auto: 
[[0.40660526]
 [0.10254681]
 [0.71645364]
 [0.55753968]]
Theoretical: 
[[0.40660526]
 [0.10254681]
 [0.71645364]
 [0.55753968]]

Input x: 
[[0.79634583]
 [0.93403905]
 [0.03381617]
 [0.76015244]]
[1.44415059]
Auto: 
[[0.55142853]
 [0.646774  ]
 [0.02341596]
 [0.526

In [ ]:
# SVM Objective (SKIP FOR NOW)

In [68]:
# PCA Objective
# I'm ignoring lambda for now
def f(x, A):
    return np.dot(np.dot(np.transpose(x), A), x) - (np.dot(np.dot(np.transpose(x), np.identity(len(x))), x) - 1)

def df(x, A):
    return np.dot((A + np.transpose(A)), x) - (2 * x)

auto = grad(f)

for i in range(10):
    x = np.random.random((4, 1))
    A = np.random.random((4, 4))
    print(f'Input x: \n{x}')
    print(f'Input A: \n{A}')
    print(f'Auto: \n{auto(x, A)}\nTheoretical: \n{df(x, A)}\n')

Input x: 
[[0.93703297]
 [0.65935178]
 [0.9700972 ]
 [0.06582908]]
Input A: 
[[0.85881797 0.99383465 0.73874019 0.81365263]
 [0.45446991 0.1363491  0.65002813 0.12932983]
 [0.00741546 0.96668632 0.61075438 0.43033126]
 [0.89907296 0.33988107 0.19228599 0.72932083]]
Auto: 
[[1.52694843]
 [1.81746751]
 [1.05093015]
 [2.48261752]]
Theoretical: 
[[1.52694843]
 [1.81746751]
 [1.05093015]
 [2.48261752]]

Input x: 
[[0.858613  ]
 [0.52157274]
 [0.32845912]
 [0.98532128]]
Input A: 
[[0.90852985 0.19515533 0.48893239 0.63873654]
 [0.34221028 0.79693298 0.51513815 0.90923742]
 [0.07598083 0.10616054 0.09588639 0.42610962]
 [0.37783789 0.37256663 0.73312572 0.57013907]]
Auto: 
[[1.31040365]
 [1.71662069]
 [1.35738482]
 [1.07505724]]
Theoretical: 
[[1.31040365]
 [1.71662069]
 [1.35738482]
 [1.07505724]]

Input x: 
[[0.88485025]
 [0.87045779]
 [0.1976084 ]
 [0.29898104]]
Input A: 
[[0.95841622 0.60329175 0.93896349 0.31649298]
 [0.08507382 0.23608544 0.34038335 0.74587944]
 [0.2400264  0.66131739 0

In [66]:
# Gaussian MLE
def f(u, x, s=1):
    total = 0
    for i in range(len(x)):
        total += np.log(np.exp(-(x[i] - u)**2/(2*s**2))/(s * np.sqrt(2*np.pi)))
    return total

def df(u, x, s=1):
    total = 0
    for i in range(len(x)):
        total += x[i] - u
    return total / (s**2)

auto = grad(f)

for i in range(10):
    u = np.random.random()
    x = np.random.random((4, 1))
    print(f'Input u: \n{u}')
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(u, x)}\nTheoretical: \n{df(u, x)}\n')

Input u: 
0.014629722702881875
Input x: 
[[0.97114827]
 [0.87160663]
 [0.02666089]
 [0.86209849]]
Auto: 
2.672995395145098
Theoretical: 
[2.6729954]

Input u: 
0.9855053632507776
Input x: 
[[0.4673613 ]
 [0.11348726]
 [0.41651723]
 [0.02720838]]
Auto: 
-2.9174472756768903
Theoretical: 
[-2.91744728]

Input u: 
0.7197105794777673
Input x: 
[[0.04985175]
 [0.02143029]
 [0.51973635]
 [0.61398246]]
Auto: 
-1.6738414699443673
Theoretical: 
[-1.67384147]

Input u: 
0.7073307395590651
Input x: 
[[0.60111553]
 [0.78359093]
 [0.45977394]
 [0.59079612]]
Auto: 
-0.39404644066608685
Theoretical: 
[-0.39404644]

Input u: 
0.6817369479059606
Input x: 
[[0.93881156]
 [0.47934669]
 [0.25221605]
 [0.42102085]]
Auto: 
-0.6355526403561989
Theoretical: 
[-0.63555264]

Input u: 
0.33477005393757786
Input x: 
[[0.81702623]
 [0.4968151 ]
 [0.04705719]
 [0.95022429]]
Auto: 
0.9720425815535781
Theoretical: 
[0.97204258]

Input u: 
0.6246638671342203
Input x: 
[[0.59978916]
 [0.07086132]
 [0.79202793]
 [0.15383

In [67]:
# Exponential MLE
def f(l, x):
    total = 0
    for i in range(len(x)):
        total += np.log(l * np.exp(-l * x[i]))
    return total

def df(l, x):
    total = 0
    for i in range(len(x)):
        total += x[i]
    return len(x)/l - total

auto = grad(f)

for i in range(10):
    l = np.random.random()
    x = np.random.random((4, 1))
    print(f'Input u: \n{l}')
    print(f'Input x: \n{x}')
    print(f'Auto: \n{auto(l, x)}\nTheoretical: \n{df(l, x)}\n')

Input u: 
0.12020621374844898
Input x: 
[[0.06218891]
 [0.05198556]
 [0.2604009 ]
 [0.53296734]]
Auto: 
32.36860729321495
Theoretical: 
[32.36860729]

Input u: 
0.9767151628516899
Input x: 
[[0.28280751]
 [0.90565076]
 [0.34767137]
 [0.54507352]]
Auto: 
2.0141566234244257
Theoretical: 
[2.01415662]

Input u: 
0.10117321093785692
Input x: 
[[0.15733344]
 [0.60408656]
 [0.72180145]
 [0.68084357]]
Auto: 
37.37209245836044
Theoretical: 
[37.37209246]

Input u: 
0.8061908537025447
Input x: 
[[0.47632469]
 [0.90406837]
 [0.26343302]
 [0.67481124]]
Auto: 
2.6429669777658753
Theoretical: 
[2.64296698]

Input u: 
0.945662735012322
Input x: 
[[0.94820595]
 [0.69445336]
 [0.10131707]
 [0.30107444]]
Auto: 
2.1847869991475575
Theoretical: 
[2.184787]

Input u: 
0.06190198522143642
Input x: 
[[0.11122577]
 [0.93845067]
 [0.90110357]
 [0.24933086]]
Auto: 
62.418172135556034
Theoretical: 
[62.41817214]

Input u: 
0.43830566674404714
Input x: 
[[0.51344541]
 [0.38487102]
 [0.25394944]
 [0.42475441]]
Au

In [65]:
# Bernoulli MLE
def f(p, a):
    total = 0
    for i in range(len(a)):
        total += np.log(np.power(p, a[i])) + np.log(np.power(1 - p, 1 - a[i]))
    return total

def df(p, a):
    total = 0
    for i in range(len(a)):
        total += a[i]/p - (1 - a[i])/(1 - p)
    return total

auto = grad(f)

for i in range(10):
    p = np.random.random()
    a = np.random.randint(0, 2, (2, 1))
    print(f'Input p: {p}')
    print(f'Input a: \n{a}')
    print(f'Auto: \n{auto(p, a)}\nTheoretical: \n{df(p, a)}\n')

Input p: 0.3389632429982151
Input a: 
[[1]
 [0]]
Auto: 
1.4373972064591791
Theoretical: 
[1.43739721]

Input p: 0.5575299449484463
Input a: 
[[1]
 [0]]
Auto: 
-0.46641431528637556
Theoretical: 
[-0.46641432]

Input p: 0.9210516470571563
Input a: 
[[1]
 [0]]
Auto: 
-11.580793261338991
Theoretical: 
[-11.58079326]

Input p: 0.5793646063432648
Input a: 
[[1]
 [1]]
Auto: 
3.4520576129481926
Theoretical: 
[3.45205761]

Input p: 0.6114810971468391
Input a: 
[[1]
 [1]]
Auto: 
3.270747058792116
Theoretical: 
[3.27074706]

Input p: 0.6667328060702606
Input a: 
[[1]
 [1]]
Auto: 
2.999702402208238
Theoretical: 
[2.9997024]

Input p: 0.24379203638776592
Input a: 
[[0]
 [1]]
Auto: 
2.7794691538585328
Theoretical: 
[2.77946915]

Input p: 0.7824332851145313
Input a: 
[[1]
 [0]]
Auto: 
-3.31822706794262
Theoretical: 
[-3.31822707]

Input p: 0.6805540997916419
Input a: 
[[0]
 [0]]
Auto: 
-6.260841033475475
Theoretical: 
[-6.26084103]

Input p: 0.4639027803154335
Input a: 
[[0]
 [1]]
Auto: 
0.2902907636

In [55]:
# Uniform MLE
def f(a, b, n):
    total = 0
    for _ in range(n):
        total += np.log(1/(b - a))
    return total

def df(a, b, n):
    return np.array([
        [n/(b-a)],
        [-n/(b-a)]
    ])

auto = grad(f)

for i in range(10):
    a = np.random.random()
    b = np.random.random()
    n = np.random.randint(1, 10)
    print(f'Input a: \n{a}')
    print(f'Input b: \n{b}')
    print(f'n = {n}')
    print(f'Auto: \n{auto(a, b, n)}\nTheoretical: \n{df(a, b, n)}\n')

Input a: 
0.9050221856736806
Input b: 
0.046639993488543086
n = 2
Auto: 
-2.3299644589651924
Theoretical: 
[[-2.32996446]
 [ 2.32996446]]

Input a: 
0.2671611148713028
Input b: 
0.1452605942657521
n = 9
Auto: 
-73.83069371067303
Theoretical: 
[[-73.83069371]
 [ 73.83069371]]

Input a: 
0.5077544291920942
Input b: 
0.44159349986297436
n = 4
Auto: 
-60.45864289635139
Theoretical: 
[[-60.4586429]
 [ 60.4586429]]

Input a: 
0.21597109871692122
Input b: 
0.25591200897315014
n = 1
Auto: 
25.036985726784895
Theoretical: 
[[ 25.03698573]
 [-25.03698573]]

Input a: 
0.46246146415499345
Input b: 
0.6993105262639839
n = 7
Auto: 
29.55468743540483
Theoretical: 
[[ 29.55468744]
 [-29.55468744]]

Input a: 
0.830718077254753
Input b: 
0.440036188861182
n = 6
Auto: 
-15.357763383071473
Theoretical: 
[[-15.35776338]
 [ 15.35776338]]

Input a: 
0.36881898609984665
Input b: 
0.9323366051171533
n = 5
Auto: 
8.872837035192045
Theoretical: 
[[ 8.87283704]
 [-8.87283704]]

Input a: 
0.7736246217746338
Input 

/Users/sunnyh2024/anaconda3/lib/python3.11/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in log
  return f_raw(*args, **kwargs)
