In [ ]:
# imports
import numpy as np

__Question 2:__

In [27]:
# initializing the matrices
X = np.array([
    [2, 3],
    [9, 1]
])

Y = np.array([
    [1, 0],
    [2, 1]
])

x = np.array([
    [1],
    [3]
])

y = np.array([
    [2],
    [4]
])

In [28]:
# 1st column of X
X[:,0]

array([2, 9])

In [29]:
# 2nd row of Y
Y[1]

array([2, 1])

In [30]:
# Bottom right value of X
X[1, 1]

1

In [31]:
# Adds X and Y
X + Y

array([[ 3,  3],
       [11,  2]])

In [32]:
# Performs X + YX
X + np.matmul(Y, X)

array([[ 4,  6],
       [22,  8]])

In [33]:
# Hadamard product of x and y
np.multiply(x, y)

array([[ 2],
       [12]])

In [34]:
# Outer product of x and y
np.outer(x, y)

array([[ 2,  4],
       [ 6, 12]])

In [35]:
# Dot product of XY
np.dot(X, Y)

array([[ 8,  3],
       [11,  1]])

In [36]:
# Inner product <X, Y>
np.inner(X, Y)

array([[ 2,  7],
       [ 9, 19]])