In [ ]:
# imports
import numpy as np

__Question 1:__

In [ ]:
# initializing the matrices
x = np.array([
    [2],
    [2],
    [6]
])

X = np.array([
    [-4, 7, 5],
    [1, -9, 2],
    [8, 3, 6]
])

Y = np.array([
    [2, 4, 6],
    [1, 0, 13],
    [-4, 5, 5]
])

Z = np.array([
    [4, -1, 0],
    [1, 1, 1]
])

Verifying the calculations

In [ ]:
# 1) x^T X Y
np.matmul(np.transpose(x), np.matmul(X, Y))

array([[-102,  418,  684]])

In [ ]:
# 2) YX
np.matmul(Y, X)

array([[ 44,  -4,  54],
       [100,  46,  83],
       [ 61, -58,  20]])

In [ ]:
# 3) 2X + 2Y + X^T Y
2*X + 2*Y + np.matmul(np.transpose(X), Y)

array([[-43,  46,  51],
       [ -3,  25, -30],
       [ -4,  66, 108]])

In [ ]:
# 4) YZ^T
np.matmul(Y, np.transpose(Z))

array([[  4,  12],
       [  4,  14],
       [-21,   6]])

In [ ]:
# 5) Z^T Z x
np.matmul(np.transpose(Z), np.matmul(Z, x))

array([[34],
       [ 4],
       [10]])