__Question 3__

In [20]:
# imports
import autograd.numpy as np
from autograd import grad

In [21]:
# initializing the matrices
x_1 = np.array([
    [1],
    [0]
])

x_2 = np.array([
    [2],
    [1]
])

x = np.array([
    [1],
    [2]
])

y = w = np.array([
    [2],
    [0]
])

A = np.array([
    [1, 0],
    [0, 2]
])

one = np.array([
    [1],
    [1]
])

In [25]:
# part 1
def f(x):
    return np.dot(np.transpose(x), np.matmul(A, x)) - np.dot(np.transpose(x), y)

def df(x):
    return np.array([2*x[0] - 2, 4*x[1]])

auto = grad(f)

for i in range(10):
    t = np.random.random((2, 1))
    print(f'Input x: \n{t}')
    print(f'Auto: \n{auto(t)}\nTheoretical: \n{df(t)}\n')

Input x: 
[[0.36090942]
 [0.38197881]]
Auto: 
[[-1.27818115]
 [ 1.52791526]]
Theoretical: 
[[-1.27818115]
 [ 1.52791526]]

Input x: 
[[0.96802346]
 [0.07312   ]]
Auto: 
[[-0.06395307]
 [ 0.29247999]]
Theoretical: 
[[-0.06395307]
 [ 0.29247999]]

Input x: 
[[0.96631723]
 [0.30978345]]
Auto: 
[[-0.06736553]
 [ 1.23913381]]
Theoretical: 
[[-0.06736553]
 [ 1.23913381]]

Input x: 
[[0.36594799]
 [0.23416165]]
Auto: 
[[-1.26810402]
 [ 0.9366466 ]]
Theoretical: 
[[-1.26810402]
 [ 0.9366466 ]]

Input x: 
[[0.98880539]
 [0.96763211]]
Auto: 
[[-0.02238922]
 [ 3.87052844]]
Theoretical: 
[[-0.02238922]
 [ 3.87052844]]

Input x: 
[[0.53246032]
 [0.96463874]]
Auto: 
[[-0.93507936]
 [ 3.85855495]]
Theoretical: 
[[-0.93507936]
 [ 3.85855495]]

Input x: 
[[0.27353887]
 [0.28848428]]
Auto: 
[[-1.45292225]
 [ 1.15393713]]
Theoretical: 
[[-1.45292225]
 [ 1.15393713]]

Input x: 
[[0.28005587]
 [0.57601223]]
Auto: 
[[-1.43988825]
 [ 2.30404891]]
Theoretical: 
[[-1.43988825]
 [ 2.30404891]]

Input x: 
[[0.19

In [26]:
# part 2
def f(x):
    return np.dot(np.transpose(x), np.matmul(A, one))

def df(x):
    return np.array([
        [1],
        [2]
    ])

auto = grad(f)

for i in range(10):
    t = np.random.random((2, 1))
    print(f'Input x: \n{t}')
    print(f'Auto: \n{auto(t)}\nTheoretical: \n{df(t)}\n')

Input x: 
[[0.05532265]
 [0.11679116]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.45898157]
 [0.68687848]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.37783696]
 [0.50257514]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.64906498]
 [0.43972361]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.47758166]
 [0.70014252]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.23782024]
 [0.89582888]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.58436773]
 [0.75954142]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.89492626]
 [0.55100457]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.69626598]
 [0.82964183]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]

Input x: 
[[0.5545165 ]
 [0.59803752]]
Auto: 
[[1.]
 [2.]]
Theoretical: 
[[1]
 [2]]



In [27]:
# part 3
def f(x: np.array):
    return np.matmul(np.transpose(x), one)

def df(x):
    return np.array([
        [1],
        [1]
    ])

auto = grad(f)

for i in range(10):
    t = np.random.random((2, 1))
    print(f'Input x: \n{t}')
    print(f'Auto: \n{auto(t)}\nTheoretical: \n{df(t)}\n')

Input x: 
[[0.67689387]
 [0.95828243]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.8597038 ]
 [0.97644448]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.71195992]
 [0.20675429]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.90990957]
 [0.10430621]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.47202017]
 [0.21287663]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.81027216]
 [0.91420122]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.20328651]
 [0.73982137]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.65089987]
 [0.51752341]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.12552452]
 [0.85888822]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]

Input x: 
[[0.28968633]
 [0.36991137]]
Auto: 
[[1.]
 [1.]]
Theoretical: 
[[1]
 [1]]



In [28]:
# part 4
def f(w):
    return np.dot(np.transpose(w), x_1) + np.dot(np.transpose(w), x_2)

def df(x):
    return np.array([
        [3],
        [1]
    ])

auto = grad(f)

for i in range(10):
    t = np.random.random((2, 1))
    print(f'Input x: \n{t}')
    print(f'Auto: \n{auto(t)}\nTheoretical: \n{df(t)}\n')

Input x: 
[[0.99347258]
 [0.57637251]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.02260881]
 [0.36562949]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.87353628]
 [0.79530911]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.80753273]
 [0.18313495]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.73035715]
 [0.80653436]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.55087984]
 [0.94772064]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.97443763]
 [0.48749385]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.19701366]
 [0.36519932]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.42007637]
 [0.61313367]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

Input x: 
[[0.34366324]
 [0.12003614]]
Auto: 
[[3.]
 [1.]]
Theoretical: 
[[3]
 [1]]

